name: Deploy Release

on:
  workflow_call:
    inputs:
      version-name:
        required: true
        type: string
      tag-name:
        required: true
        type: string
      release-notes:
        required: false
        type: string
        default: 'TBD'
      publish-prerelease:
        required: false
        default: false
        type: boolean

jobs:
  build-mdl-sdk:
    name: Build MDL SDK
    uses: ./.github/workflows/build-mdl-sdk.yml
    with:
      cache-key-prefix: MDL-SDK_${{ vars.MDL_SDK_VERSION }}

  build-usd2508:
    name: Build for USD v25.08
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 25.08
      mdl-sdk-cache-key-prefix: MDL-SDK_${{ vars.MDL_SDK_VERSION }}
      upload-install-artifacts: true
      run-graphical-tests: true

  build-usd2505:
    name: Build for USD v25.05
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 25.05
      mdl-sdk-cache-key-prefix: MDL-SDK_${{ vars.MDL_SDK_VERSION }}
      upload-install-artifacts: true
      run-graphical-tests: true

  build-usd2502:
    name: Build for USD v25.02
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 25.02
      mdl-sdk-cache-key-prefix: MDL-SDK_${{ vars.MDL_SDK_VERSION }}
      upload-install-artifacts: true
      run-graphical-tests: true

  build-usd2411:
    name: Build for USD v24.11
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 24.11
      mdl-sdk-cache-key-prefix: MDL-SDK_${{ vars.MDL_SDK_VERSION }}
      upload-install-artifacts: true
      run-graphical-tests: true

  build-houdini20:
    name: Build for Houdini 20.0
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-houdini20.yml
    with:
      mdl-sdk-cache-key-prefix: MDL-SDK_${{ vars.MDL_SDK_VERSION }}

  build-blender43:
    name: Build for Blender 4.3
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-blender43.yml
    with:
      mdl-sdk-cache-key-prefix: MDL-SDK_${{ vars.MDL_SDK_VERSION }}

  deploy-release:
    name: Deploy Release
    needs: [build-usd2508, build-usd2505, build-usd2502, build-usd2411, build-houdini20, build-blender43]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Deploy release
        uses: softprops/action-gh-release@d4e8205d7e959a9107da6396278b2f1f07af0f9b
        with:
          name: ${{ inputs.version-name }}
          body: ${{ inputs.release-notes }}
          files: |
            *.tar.gz
            *.zip
          fail_on_unmatched_files: true
          tag_name: ${{ inputs.tag-name }}
          prerelease: ${{ inputs.publish-prerelease }}
          draft: ${{ ! inputs.publish-prerelease }}
          make_latest: true
