name: Validation Build

on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-mdl-sdk:
    name: Build MDL SDK
    uses: pablode/MDL-SDK/.github/workflows/main.yml@GA-2023.0.4-ubuntu22
    with:
      cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}

  build-2502:
    name: Build gatling for USD v25.02 (Release)
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 25.02
      mdl-sdk-cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}
      run-graphical-tests: true
      upload-test-artifacts: true

  build-2411:
    name: Build gatling for USD v24.11 (Release)
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 24.11
      mdl-sdk-cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}
      run-graphical-tests: true
      upload-test-artifacts: true

  build-2408:
    name: Build gatling for USD v24.08 (Release)
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 24.08
      mdl-sdk-cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}
      run-graphical-tests: true
      upload-test-artifacts: true

  build-2405:
    name: Build gatling for USD v24.05 (Release)
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 24.05
      mdl-sdk-cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}

  build-2403:
    name: Build gatling for USD v24.03 (Release)
    needs: build-mdl-sdk
    uses: ./.github/workflows/build-usd.yml
    with:
      usd-version: 24.03
      mdl-sdk-cache-key-prefix: ${{ vars.MDL_SDK_CACHE_KEY_PREFIX }}
